version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - cd layers/dependencies
      - pip install -r requirements.txt -t python/
      - cd ../..
  build:
    commands:
      - sam build
      - sam package --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1jzba95imlkz8 --output-template-file packaged.yml
artifacts:
  files:
    - packaged.yml