version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - cd layers/dependencies
      - mkdir -p python
      - pip install -r requirements.txt -t python/ --upgrade
      - cd ../..
  build:
    commands:
      - sam build --use-container
      - sam package --s3-bucket codepipeline-us-west-2-191184544132 --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml